export { CategoryModule } from './category/category.module';
export { FileModule } from './files/file.module';
export { InventoryModule } from './inventory/inventory.module';
export { UserModule } from './users/users.module';
export { ProductModule } from './product/product.module';
export { AddressModule } from './address/address.module';
export { CommentModule } from './comment/comment.module';
export { DiscountModule } from './discount/discount.module';
export { FavoriteModule } from './favorite/favorite.module';
